### ISSUE TITLE
What folders or files can be considered assets needed to run the game on Wii U?

### ISSUE THREAD

**Issue by wikiblog0** [MaikelChan/PlumbersDontWearTies-SDL2#2]
Hi
First, I want to thank you for give a new port game for the Wii U and to enter in the Wii U homebrew programming.

Second, I want to play the game but I don't know which files or folders are necessary to launch the game. I know that in the "how to run" section you say that put "all the assets and folders of the game in the Data folder". But I'm not sure which file or folders can be considered like assets, so I paste all the files and folders of the pc version in the Data folder and I try to launch the game in the Wii U but it doesn't work. Lately I found the repository of the PSVita port of the game, and this repository specified which folders and files is needed to run the psvita port. So I supposed that maybe this files are the assets to run the game in Wii U. I paste the folders and files and I try to launch the game in the Wii U but I fail again. 

So, could you specified which folders or files are necessary to run the game in the readme.md like in the repository of the PSVita port?

I leave you the link of the psvita port repository: https://github.com/Serph/PlumbersDontWearTies-SDL-vita 
In the section of install, specified which folders and files are needed to run the game. (Maybe some other file is missing to run it on wii u)

Finally, I want to ask you if you will continue to port games or applications to Wii U in the future? Because I would like that the next project was a multimedia center for Wii U like Movian. If you are interested I can share the link of the github repository of Movian and the main page of the application where is it located the source code of the last version.

I thank you in advance for your help. 

Best Regards.

**Comment by MaikelChan** [comment]
Hi! Sorry for the late reply.

It looks like you might have seen the Windows instructions instead of the WiiU ones. Here's a link: https://github.com/MaikelChan/PlumbersDontWearTies-SDL/tree/wiiu

Basically, create a folder called "PlumbersDontWearTies" at the root of your SD card, and put all the assets of the PC version there.

I'm not planning new ports for WiiU now, I'm busy with other stuff. But who knows in the future. But if that happens, it would probably be something I have special interest in or that I have worked on.

Hope this helps!

**Comment by wikiblog0** [comment]
Hi, 
Don't worry, thanks for replying. 

I didn't realize that each platform had its own instruction branch, my bad. Thanks for the Wii U link's branch!
This time I think I'm not going to have any problems running the game on Wii U anymore.

I hope you continue with the projects of game ports or developing applications for consoles, especially for Wii, 3DS and Wii U. Since I have really enjoyed playing 3D space pinball with my brother on both the Wii and the 3DS. 

Thank you for such a beautiful experience and for your contributions!!
